// <auto-generated />
namespace VisibilityPortal_BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Extend_User_UserRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Extend_User_UserRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201910250811582_Extend_User_UserRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
