// <auto-generated />
namespace VisibilityPortal_BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Set_DBGenerated_Option_to_ApplicationUser_CreatedOn_ModifiedOn_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Set_DBGenerated_Option_to_ApplicationUser_CreatedOn_ModifiedOn_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201910271650359_Set_DBGenerated_Option_to_ApplicationUser_CreatedOn_ModifiedOn_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
