// <auto-generated />
namespace VisibilityPortal_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Rename_IsActivated_to_IsEnabled_on_PortalModuleForClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_IsActivated_to_IsEnabled_on_PortalModuleForClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201911150829418_Rename_IsActivated_to_IsEnabled_on_PortalModuleForClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
