// <auto-generated />
namespace VisibilityPortal_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_Route_Prefix_to_PortalModule_and_CreatedBy_to_PortalModuleForClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_Route_Prefix_to_PortalModule_and_CreatedBy_to_PortalModuleForClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201911060808459_Add_Route_Prefix_to_PortalModule_and_CreatedBy_to_PortalModuleForClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
