// <auto-generated />
namespace CallCenter_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_FloatResource_AlertType_FloatResourceAlertForClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_FloatResource_AlertType_FloatResourceAlertForClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201912190750370_Add_FloatResource_AlertType_FloatResourceAlertForClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
