// <auto-generated />
namespace CallCenter_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FloatResourceAlertForClient_Change_CreatedOn_and_ModifiedOn_dates_to_UTC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FloatResourceAlertForClient_Change_CreatedOn_and_ModifiedOn_dates_to_UTC));
        
        string IMigrationMetadata.Id
        {
            get { return "201912310913098_FloatResourceAlertForClient_Change_CreatedOn_and_ModifiedOn_dates_to_UTC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
